CREATE TABLE ROLES
(
    RID SERIAL PRIMARY KEY,
    RNAME VARCHAR(255) UNIQUE NOT NULL,
    RDESCRIPTION VARCHAR(255) NOT NULL,
    RBASESAL FLOAT NOT NULL,
    RBASELEAVE INT NOT NULL,
    
);

CREATE TABLE EMPLOYEES
(
    ENUMBER SERIAL PRIMARY KEY,
    EFNAME VARCHAR(100) NOT NULL,
    EMIDNAME VARCHAR(250), 
    ESURNAME VARCHAR(250) NOT NULL,
    EDOB DATE NOT NULL,
    EBONUS FLOAT NOT NULL,
    ERID INTEGER NOT NULL,
    EMANAGERID INTEGER,
    FOREIGN KEY (ERID) REFERENCES ROLES (RID)
)
