name: deploy-hrizon

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        cd backend/hrizon
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd backend/hrizon
        docker build -t d1scrd/hrizon:latest .
        docker push d1scrd/hrizon:latest

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          docker pull d1scrd/hrizon:latest
          docker stop hrizon || true
          docker rm hrizon || true
          docker run -d --name hrizon -p 8001:8001 d1scrd/hrizon:latest
